apiVersion: apps/v1
kind: Deployment
metadata:
  name: bankingfinance
  labels:
    app: bankingfinance
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bankingfinance
  template:
    metadata:
      labels:
        app: bankingfinance
    spec:
      containers:
      - name: bankingfinance-container
        image: murali90102/bankingfinance
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: bankingfinance
  labels:
    app: bankingfinance
spec:
  selector:
    app: bankingfinance

  type: NodePort
  ports:
  - nodePort: 31001
    port: 8081
    targetPort: 8081
